### PR TITLE
Use geom_step instead

### PR DESCRIPTION
**Pull request by MatthieuStigler**
Maybe could just use `geom_step` instead of `geom_line` for the treatment indicator?

### CODE REVIEW

**Comment by hhsievertsen** [comment]
Hi Matthieu, 
thanks for the two good changes! I merged them into master. 
Hans

**Comment by MatthieuStigler** [comment]
Nice, I'm glad it can be helpful. Did I get the ATT right, `ATT1 <- input$group2treatmenteffect  *mt2^(T-T2)` ? Thanks!

**Comment by hhsievertsen** [comment]
Yes. I realised that you used the actual (DGP) ATT for each group and not the estimated ATT in creating the table (that might have been intentional, and if not, then due to my messy coding), but I changed the layout now to make it clearer.

**Comment by MatthieuStigler** [comment]
Oh I should have been more specific on this, actually my intent was to show the true DGP ATT.  I think this is useful for pedagogical purpose to understand what we aim to estimate. 

In this case may I suggest to add a 4th row with the DPG VALUE and something like "true ATT"? Or maybe as a third column, allowing to add one bias column?

**Comment by hhsievertsen** [comment]
Ah makes sense. I guess I was just too lazy too calculate the ATT DGP when it can change over time (ie ATT_baseline*sum(1+r)^i) but I'll add your great suggestion asap.

**Comment by hhsievertsen** [comment]
Hi Matthieu, I finally got around to add the DGP to the table as you suggested. Thanks for the great suggestion. And thanks for adding geom_step(). I actually didn't know about that one!
Thanks for your contributions on this.

**Pull request merged**
